### ISSUE TITLE
allow ingest pipeline to specify object types using jq

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/ogc-na-tools#11]
line 174 of ingest_json.py only allows static paths to be used

'  for json_path in context.get('types', {}).keys():
        if json_path in ('.', '$'):
            continue
        try:
            json_path_parse(json_path)'

where as transform allow jq content.

can types reference variables set by the transform logic - or a global variables section with jq that both sections can access?

**Comment by avillar** [comment]
The jq transforms are "self-contained" (and independent from each other); the only output that we get from each transform is the resulting, transformed JSON.

A global variables section could be doable. We'd have to decide when they can be used (inside jq transforms, in `types` paths and values, and inside `context` paths and values? in `$VARIABLE` format?).

Additionally, do you have simple values in mind (e.g., strings) or are you also thinking about mappings (similar to what we did with the concept scheme dictionary)?

**Comment by rob-metalinkage** [comment]
solved using @avillar suggestion - add line 

```    .[].type = $CONCEPTTYPE |```

to transform pipeline
