### ISSUE TITLE
wrong CRS rewriting

### ISSUE THREAD

**Issue by pebau** [opengeospatial/ogc-na-tools#13]
In compound CRSs, like
``
​https://opengis.net/def/crs-compound?1=https://opengis.net/def/crs/OGC/0/AnsiDate?axis-label="time"&2=https://opengis.net/def/crs/EPSG/0/28992
``

opengis.net redirects the first component to /crs/def instead of /def/crs:

``
1=https://opengis.net/crs/def/OGC/0/AnsiDate?axis-label="time"
``

...and the request fails.

This is problem with the redirect, not with the resolver implementation: it works fine with endpoint crs.rasdaman.com, e.g.
``
​https://crs.rasdaman.com/def/crs-compound?1=https://crs.rasdaman.com/def/crs/OGC/0/AnsiDate?axis-label="time"&2=https://crs.rasdaman.com/def/crs/EPSG/0/28992
``

**Comment by ghobona** [comment]
@pebau Thanks for reporting the issue. I have verified the issue and asked the Infrastructure Office to address it.

**Comment by kstegemoller** [comment]
@pebau @ghobona OGC uses the www.opengis.net domain and not the opengis.net domain.
Fixing the URL above to use www.opengis.net does work. Are you proposing different?

These all work...
* https://www.opengis.net/def/crs-compound?1=https://www.opengis.net/def/crs/OGC/0/AnsiDate%3faxis-label=%2522time%2522&2=https://www.opengis.net/def/crs/EPSG/0/28992
or mixed protocols
* https://www.opengis.net/def/crs-compound?1=http://www.opengis.net/def/crs/OGC/0/AnsiDate%3faxis-label=%2522time%2522&2=http://www.opengis.net/def/crs/EPSG/0/28992
or http protocol
* http://www.opengis.net/def/crs-compound?1=http://www.opengis.net/def/crs/OGC/0/AnsiDate%3faxis-label=%2522time%2522&2=http://www.opengis.net/def/crs/EPSG/0/28992

**Comment by ghobona** [comment]
@kstegemoller Well spotted. You are right, the URLs should use [www.opengis.net](http://www.opengis.net/).

**Comment by pebau** [comment]
thanks for clarifying, we thought that opengis.net = www.opengis.net . Closing now.
