### ISSUE TITLE
Refactor and add READMes to each tool

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/ogc-na-tools#8]
Making each tool more accessible for collaborative input means a README to explain,  playgrounds for any workflows etc.

**Comment by avillar** [comment]
We have [this](https://opengeospatial.github.io/ogc-na-tools/) which is automatically generated from what is in the `docs` directory and from the docstrings in the code itself.

What we should maybe do in the README is 1) include a brief description of each tool, 2) link to the docs (both in general and inside the tool descriptions).

**Comment by avillar** [comment]
Done. Please check whether more detail is necessary.
